### DO NOT EDIT THIS FILE ###
export OB_TYPE          := simple
export OB_DEFCONFIG_DIR := ${CURDIR}/configs
export OB_CONTAINER_DIR := ${CURDIR}/configs/container

include third-party/openbar/core/main.mk
### DO NOT EDIT THIS FILE ###
